name: Deploy API
on:
  push:
    branches:
      - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 10
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          command: deploy --env demo
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "src/api"